# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findmyburritto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='burritos_burned',
            field=models.IntegerField(blank=True, null=True, verbose_name='burritos burned off'),
        ),
    ]
